/**
 * @file tests/integration/members.test.js
 * @description Integration tests for the Members domain.
 * Validates CRUD operations, role-based access control, and pagination data structure.
 */

import request from 'supertest';
import mongoose from 'mongoose';
import jwt from 'jsonwebtoken';
import app from '../../app.js';
import User from '../../src/models/members/User.js';
import { env } from '../../src/config/env.js';

const generateAuthCookie = async (role = 'Coordinador') => {
  const userId = new mongoose.Types.ObjectId();
  const mockUser = new User({
    _id: userId,
    username: `membertester_${Date.now()}`,
    password: 'hashed_password',
    role: role,
    isActive: true
  });
  
  await mockUser.save({ validateBeforeSave: false });
  const token = jwt.sign({ id: userId }, env.JWT_SECRET, { expiresIn: '1h' });
  return `token=${token}`;
};

describe('Integration: Members API', () => {
  
  describe('GET /api/members', () => {
    it('should return a paginated response structure for authenticated users', async () => {
      const cookie = await generateAuthCookie('Subcoordinador');
      
      const response = await request(app)
        .get('/api/members?page=1&limit=5')
        .set('Cookie', [cookie]);

      expect(response.status).toBe(200);
      expect(response.body.success).toBe(true);
      expect(Array.isArray(response.body.data)).toBe(true);
      
      // Verifying the pagination metadata object generated by your utility
      expect(response.body.pagination).toHaveProperty('total');
      expect(response.body.pagination).toHaveProperty('totalPages');
      expect(response.body.pagination).toHaveProperty('currentPage', 1);
      expect(response.body.pagination).toHaveProperty('perPage', 5);
    });
  });

describe('GET /api/members', () => {
    it('should return a paginated response structure for authenticated users', async () => {
      const cookie = await generateAuthCookie('Subcoordinador');
      
      const response = await request(app)
        .get('/api/members?page=1&limit=5')
        .set('Cookie', [cookie]);

      // Captura de depuración para exponer el error interno
      if (response.status === 500) {
        console.error('DETALLE DEL ERROR 500 EN MEMBERS:');
        console.error(JSON.stringify(response.body, null, 2));
      }

      expect(response.status).toBe(200);
      expect(response.body.success).toBe(true);
      expect(Array.isArray(response.body.data)).toBe(true);
      
      expect(response.body.pagination).toHaveProperty('total');
      expect(response.body.pagination).toHaveProperty('totalPages');
      expect(response.body.pagination).toHaveProperty('currentPage', 1);
      expect(response.body.pagination).toHaveProperty('perPage', 5);
    });
  });
});